In [1]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"pankajlamgria","key":"1a45498f53b0668c01ddc274770b9cdb"}'}

In [2]:
!mkdir ~/.kaggle


In [3]:
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


In [8]:
!kaggle datasets download -d lightningforpython/spam-or-not


Dataset URL: https://www.kaggle.com/datasets/lightningforpython/spam-or-not
License(s): Apache 2.0
  0% 0.00/207k [00:00<?, ?B/s]
100% 207k/207k [00:00<00:00, 73.4MB/s]


In [9]:
!unzip spam-or-not.zip


Archive:  spam-or-not.zip
  inflating: spam.csv                


In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv("/content/spam.csv")
print(df.head(10))

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...


In [12]:
print(df.shape)

(5572, 2)


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB
None


In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Category']=le.fit_transform(df['Category'])

In [ ]:
print(df.head(10))

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
5         1  FreeMsg Hey there darling it's been 3 week's n...
6         0  Even my brother is not like to speak with me. ...
7         0  As per your request 'Melle Melle (Oru Minnamin...
8         1  WINNER!! As a valued network customer you have...
9         1  Had your mobile 11 months or more? U R entitle...


In [14]:
print(df['Message'][1])

Ok lar... Joking wif u oni...


In [15]:
print(len(df['Message'][0]))

111


In [16]:
! nltk.download()

/bin/bash: -c: line 2: syntax error: unexpected end of file


In [22]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [18]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
stwd=stopwords.words('english')
lem=WordNetLemmatizer()
x=np.array(df['Message'])

In [ ]:
print(x)

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']


In [23]:
for i in range(0,len(x)):
  sent=x[i]
  words=word_tokenize(sent)
  words=[lem.lemmatize(word) for word in words if word not in stwd]
  x[i]=' '.join(words)
print(x)

['Go jurong point , crazy .. Available bugis n great world la e buffet ... Cine got amore wat ...'
 'Ok lar ... Joking wif u oni ...'
 "Free entry 2 wkly comp win FA Cup final tkts 21st May 2005 . Text FA 87121 receive entry question ( std txt rate ) T & C 's apply 08452810075over18 's"
 ... 'Pity , * mood . So ... suggestion ?'
 "The guy bitching I acted like 'd interested buying something else next week gave u free"
 'Rofl . Its true name']


In [24]:
for i in range(0,len(x)):
  x[i]=x[i].lower()
print(x)

['go jurong point , crazy .. available bugis n great world la e buffet ... cine got amore wat ...'
 'ok lar ... joking wif u oni ...'
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005 . text fa 87121 receive entry question ( std txt rate ) t & c 's apply 08452810075over18 's"
 ... 'pity , * mood . so ... suggestion ?'
 "the guy bitching i acted like 'd interested buying something else next week gave u free"
 'rofl . its true name']


In [25]:
df['Message']=x

In [177]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
vector_x=vectorizer.fit_transform(x).toarray()

In [208]:
print(vector_x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [180]:
print(vector_x.shape)

(5572, 8322)


In [ ]:
print(vector_x.shape)

(5572, 8322)


In [202]:
xtrain2,xtest2,ytrain2,ytest2=train_test_split(vector_x,df['Category'],test_size=0.2,random_state=42)

In [203]:
print(xtrain2.shape)
print(xtest2.shape)

(4457, 8322)
(1115, 8322)


In [205]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(xtrain2.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Example output layer for binary classification
])

In [206]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(xtrain2,ytrain2,epochs=5)

Epoch 1/5
140/140 [==============================] - 1s 3ms/step - loss: 0.3112 - accuracy: 0.8970
Epoch 2/5
140/140 [==============================] - 0s 3ms/step - loss: 0.0457 - accuracy: 0.9883
Epoch 3/5
140/140 [==============================] - 0s 3ms/step - loss: 0.0101 - accuracy: 0.9975
Epoch 4/5
140/140 [==============================] - 0s 3ms/step - loss: 0.0030 - accuracy: 0.9998
Epoch 5/5
140/140 [==============================] - 1s 4ms/step - loss: 0.0013 - accuracy: 1.0000


In [207]:
print(model.evaluate(xtest,ytest))

35/35 [==============================] - 0s 4ms/step - loss: 0.0492 - accuracy: 0.9874
[0.04921310022473335, 0.9874439239501953]


In [ ]:
print(vectorizer.get_feature_names_out())

['00' '000' '000pes' ... 'èn' 'ú1' '〨ud']


In [48]:
print(vector_x.shape)
print(df['Category'].shape)

(5572, 8322)
(5572,)


In [50]:
y=df['Category']
y=np.array(y)
y=y.reshape((1,len(y)))

In [53]:
y=y.T

In [54]:
print(y.shape)

(5572, 1)


In [115]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(vector_x,y,test_size=0.2,random_state=42)

In [117]:
print(x_train.shape)
y_train=y_train.reshape(y_train.shape[0],)
print(y_train.shape)

(4457, 8322)
(4457,)


In [120]:
y_test=y_test.reshape(y_test.shape[0],)

In [119]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(100,100),alpha=.1,max_iter=10)
clf=mlp.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


In [121]:
res=clf.predict(x_test)
print(np.bincount(res),np.bincount(y_test))

[980 135] [966 149]


In [123]:
print("Accuracy:",np.sum(res==y_test)/len(y_test))

Accuracy: 0.9874439461883409


In [124]:
print(x)

['go jurong point , crazy .. available bugis n great world la e buffet ... cine got amore wat ...'
 'ok lar ... joking wif u oni ...'
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005 . text fa 87121 receive entry question ( std txt rate ) t & c 's apply 08452810075over18 's"
 ... 'pity , * mood . so ... suggestion ?'
 "the guy bitching i acted like 'd interested buying something else next week gave u free"
 'rofl . its true name']


In [127]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [131]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)
sequences = tokenizer.texts_to_sequences(x)
print(sequences)


[[14, 4185, 387, 695, 601, 1248, 45, 83, 284, 1249, 105, 2837, 1250, 20, 4186, 96], [15, 298, 1421, 424, 2, 1829], [16, 440, 4, 731, 829, 134, 1830, 1035, 602, 1831, 2206, 217, 2207, 25, 1830, 1832, 299, 440, 341, 884, 32, 275, 141, 76, 5, 353, 2838, 5], [2, 204, 78, 342, 2839, 2, 76, 113, 78], [952, 1, 9, 55, 14, 885, 120, 183, 425], [732, 89, 1251, 5, 121, 60, 5, 195, 46, 1, 426, 21, 354, 43, 1833, 15, 324, 884, 4187, 29, 289, 190, 2840], [173, 523, 21, 343, 309, 629, 21, 2841, 4188], [202, 196, 953, 2208, 2209, 1834, 2210, 2211, 2212, 258, 552, 954, 1603, 764, 355, 955, 106, 954], [654, 202, 765, 372, 187, 398, 2842, 1252, 110, 886, 108, 87, 3, 2843, 87, 373, 2844, 471, 887, 220], [453, 47, 630, 231, 2, 36, 1134, 441, 285, 454, 47, 300, 16, 3, 71, 47, 441, 90, 16, 2845], [1, 7, 191, 92, 37, 184, 9, 27, 242, 248, 1135, 177, 54, 1, 114, 4189, 399, 38], [1835, 281, 134, 122, 455, 631, 830, 400, 427, 32, 2846, 29, 1836, 310, 151, 18, 2847, 207, 2848, 353, 51, 1422, 11, 655], [160, 10, 7

In [132]:
max_length = 20
padded_sequences = pad_sequences(sequences, maxlen=max_length)
print(padded_sequences)


[[   0    0    0 ...   20 4186   96]
 [   0    0    0 ...  424    2 1829]
 [ 602 1831 2206 ...  353 2838    5]
 ...
 [   0    0    0 ... 1245   58 4180]
 [   0    0    0 ...  968    2   16]
 [   0    0    0 ...  116  423  211]]


[   0    0    0    0   14 4185  387  695  601 1248   45   83  284 1249
  105 2837 1250   20 4186   96]


In [137]:
print(tokenizer.word_index)

{'i': 1, 'u': 2, 'call': 3, '2': 4, "'s": 5, 'get': 6, "'m": 7, 'ur': 8, "n't": 9, 'you': 10, '4': 11, 'gt': 12, 'lt': 13, 'go': 14, 'ok': 15, 'free': 16, 'know': 17, 'day': 18, 'come': 19, 'got': 20, 'like': 21, 'good': 22, 'time': 23, "'ll": 24, 'text': 25, 'love': 26, 'want': 27, 'no': 28, 'send': 29, 'one': 30, 'need': 31, 'txt': 32, 'going': 33, 'ü': 34, 'how': 35, 'r': 36, 'home': 37, 'today': 38, 'lor': 39, 'stop': 40, 'sorry': 41, 'see': 42, 'still': 43, 'take': 44, 'n': 45, 'back': 46, 'mobile': 47, 'da': 48, 'do': 49, 'but': 50, 'reply': 51, 'dont': 52, 'we': 53, 'k': 54, 'think': 55, 'if': 56, 'tell': 57, 'so': 58, 'hi': 59, 'week': 60, 'phone': 61, "''": 62, 'new': 63, 'please': 64, 'later': 65, 'pls': 66, 'it': 67, 'just': 68, 'what': 69, 'my': 70, 'the': 71, 'make': 72, 'msg': 73, 'night': 74, 'dear': 75, 'c': 76, '1': 77, 'say': 78, 'well': 79, 'your': 80, 'message': 81, 'much': 82, 'great': 83, 'oh': 84, 'hope': 85, 'and': 86, 'claim': 87, 'thing': 88, 'hey': 89, 'co': 

In [138]:
print(len(tokenizer.word_index))

8457


In [139]:
print(padded_sequences.shape)

(5572, 20)


In [140]:
xtrain,xtest,ytrain,ytest=train_test_split(padded_sequences,y,test_size=0.2,random_state=42)

In [141]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

In [167]:
vocab_size = len(tokenizer.word_index) + 1  # add 1 for padding token
embedding_dim = 50  # example embedding dimension


In [168]:
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length),
    Flatten(),
    Dense(64,activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Example output layer for binary classification
])

In [169]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [170]:
model.fit(xtrain, ytrain, epochs=10, batch_size=32)

Epoch 1/10
140/140 [==============================] - 15s 94ms/step - loss: 0.1901 - accuracy: 0.9338
Epoch 2/10
140/140 [==============================] - 5s 35ms/step - loss: 0.0225 - accuracy: 0.9939
Epoch 3/10
140/140 [==============================] - 3s 20ms/step - loss: 0.0058 - accuracy: 0.9991
Epoch 4/10
140/140 [==============================] - 2s 15ms/step - loss: 0.0023 - accuracy: 0.9996
Epoch 5/10
140/140 [==============================] - 2s 16ms/step - loss: 0.0010 - accuracy: 0.9998
Epoch 6/10
140/140 [==============================] - 2s 13ms/step - loss: 3.3177e-04 - accuracy: 1.0000
Epoch 7/10
140/140 [==============================] - 1s 6ms/step - loss: 1.1332e-04 - accuracy: 1.0000
Epoch 8/10
140/140 [==============================] - 1s 9ms/step - loss: 5.7472e-05 - accuracy: 1.0000
Epoch 9/10
140/140 [==============================] - 1s 6ms/step - loss: 4.3037e-05 - accuracy: 1.0000
Epoch 10/10
140/140 [==============================] - 2s 13ms/step - loss: 3

In [175]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 50)            422900    
                                                                 
 flatten (Flatten)           (None, 1000)              0         
                                                                 
 dense_36 (Dense)            (None, 64)                64064     
                                                                 
 dense_37 (Dense)            (None, 32)                2080      
                                                                 
 dense_38 (Dense)            (None, 1)                 33        
                                                                 
Total params: 489077 (1.87 MB)
Trainable params: 489077 (1.87 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [171]:
print(model.evaluate(xtest,ytest))

35/35 [==============================] - 0s 2ms/step - loss: 0.0507 - accuracy: 0.9901
[0.05072668567299843, 0.9901345372200012]


In [172]:
res=model.predict(xtest)

35/35 [==============================] - 0s 2ms/step


In [173]:
out=[1 if i>=.5 else 0 for i in res]

In [174]:
print(out)
print(ytest.flatten())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 

In [176]:
print(x)

['go jurong point , crazy .. available bugis n great world la e buffet ... cine got amore wat ...'
 'ok lar ... joking wif u oni ...'
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005 . text fa 87121 receive entry question ( std txt rate ) t & c 's apply 08452810075over18 's"
 ... 'pity , * mood . so ... suggestion ?'
 "the guy bitching i acted like 'd interested buying something else next week gave u free"
 'rofl . its true name']


In [178]:
\

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
